# fallback parameters. Relative path from the config/ directory
includes: defaults.yaml

model: gns
num_mp_steps: 2
num_mlp_layers: 1
latent_dim: 4
input_seq_length: 3

batch_size: 100
lr_start: 5.e-4
lr_final: 1.e-6
lr_decay_steps: 3.e+5
noise_std: 0.0
pushforward:
  steps: [-1]
  unrolls: [0]
  probs: [1]

mode: train
eval_n_trajs: 5
split_valid_traj_into_n: 5

wandb: False
wandb_project: hook

data_dir: datasets/Hook2_debug

log_steps: 10
eval_steps: 50
