data_dir: datasets/3D_LDC_8160_10kevery100

model: 
  name: segnn
  num_mp_steps: 10
  latent_dim: 64

train:
  isotropic_norm: True

optimizer:
  lr_start: 5.e-4

logging:
  wandb_project: ldc_3d

neighbors:
  multiplier: 2.0