extends: lagrangebench/defaults.py

main:
  data_dir: datasets/3D_LDC_8160_10kevery100

model: 
  name: segnn
  num_mp_steps: 10
  latent_dim: 64
  isotropic_norm: True

train:
  optimizer:
    lr_start: 5.e-4

logging:
  wandb_project: ldc_3d

neighbors:
  multiplier: 2.0