extends: LAGRANGEBENCH_DEFAULTS

main:
  dataset_path: datasets/2D_TGV_2500_10kevery100

model: 
  name: segnn
  num_mp_steps: 10
  latent_dim: 64
  isotropic_norm: True

train:
  optimizer:
    lr_start: 5.e-4

logging:
  wandb_project: tgv_2d
