# fallback parameters. Relative path from the config/ directory
extends: defaults.yaml

noise_std: 1.e-4

mode: train
n_rollout_steps: 20
eval_n_trajs: 10
split_valid_traj_into_n: 1

wandb: False
wandb_project: tgv_3d

data_dir: /home/atoshev/data/3D_TGV_8000_10kevery100
