extends: lagrangebench/defaults.py

main:
  dataset_path: datasets/3D_TGV_8000_10kevery100

model: 
  name: segnn
  num_mp_steps: 10
  latent_dim: 64
  isotropic_norm: True

train:
  optimizer:
    lr_start: 5.e-4

logging:
  wandb_project: tgv_3d
