# fallback parameters. Relative path from the config/ directory
includes: defaults.yaml

model: hae_segnn
num_mp_steps: 10
latent_dim: 64

batch_size: 1
lr_start: 1.e-3
lr_final: 1.e-6
lr_decay_steps: 1.e+5
noise_std: 3.e-5
isotropic_norm: True
attribute_embedding_blocks: 1 # linear
right_attribute: False
velocity_aggregate: all
pushforward:
  steps: [-1, 100000, 125000, 150000, 175000, 200000]
  unrolls: [0, 1, 2, 3, 4, 5]
  probs: [16, 2, 1, 1, 1, 1]

segnn_norm: instance

mode: train
eval_n_trajs: 10
split_valid_traj_into_n: 10

wandb: False
wandb_project: rpf

data_dir: datasets/RPF100k1every10
