# Model settings
# Model architecture name. gns, segnn, egnn
model:
# Length of the position input sequence
input_seq_length: 6
# Number of message passing steps
num_mp_steps: 10
# Number of MLP layers
num_mlp_layers: 2
# Hidden dimension
latent_dim: 128
# Load checkpointed model from this directory
model_dir:
# SEGNN only parameters
# Steerable attributes level
lmax_attributes: 1
# Level of the hidden layer
lmax_hidden: 1
# SEGNN normalization. instance, batch, none
segnn_norm: instance
# SEGNN velocity aggregation. avg or last
velocity_aggregate: avg

# Optimization settings
# Max steps
step_max: 2.e+7
# Batch size
batch_size: 2
# Starting learning rate
lr_start: 1.e-4
# Final learning rate after decay
lr_final: 1.e-6
# Rate of learning rate decay
lr_decay_rate: 0.1
# Number of steps for the learning rate to decay
lr_decay_steps: 5.e+6
# Standard deviation for the additive noise
noise_std: 0.00067
# Whether to use magnitudes or not
magnitudes: False
# Whether to normalize inputs and outputs with the same value in x, y, ans z.
isotropic_norm: False
# Parameters related to the push-forward trick
pushforward:
  # At which training step to introduce next unroll stage, e.g. [-1, 20000, 50000]
  steps: [-1,]
  # For how many steps to unroll, e.g. [0, 1, 20]
  unrolls: [0,]
  # Which probability ratio to keep between the unrolls, e.g. [5, 4, 1]
  probs: [1.,]

# Loss settings
# Loss weight for position, acceleration, and velocity components
loss_weight:
  acc: 1.0

# Run settings
# train, infer
mode:
# Dataset directory
data_dir:
# Number of rollout steps. If "-1", then defaults to sequence_length - input_seq_len.
# n_rollout_steps must be <= ground truth len. For extrapolation use n_extrap_steps
n_rollout_steps: -1
# Into how many parts to split each validation trajectory for inference
split_valid_traj_into_n: 1
# Number of evaluation trajectories
eval_n_trajs: 5
# Number of extrapolation steps
n_extrap_steps: 0
# Whether to use test or validation split
test: False
# Seed
seed: 0
# Cuda device
gpu: 0
# Double precision everywhere other than the ML model
f64: True

# Logging settings
# Use wandb for logging
wandb: False
wandb_project: False
# Number of steps between training logging
log_steps: 1000
# Number of steps between evaluation
eval_steps: 5000
# Number of steps between checkpoints
save_steps: 5000
# Checkpoint directory
ckp_dir: ckp
# Rollout/metrics directory
rollout_dir:
# Rollout storage format. vtk, pkl, none
out_type: none
# List of metrics. mse, mae, sinkhorn, e_kin
metrics:
  - mse
