# Model settings
# Model architecture name. gns, segnn, segnn_attention, segnn_rewind
model:
# Length of the position input sequence
input_seq_length: 6
# Number of message passing steps
num_mp_steps: 10
# Number of MLP layers
num_mlp_layers: 2
# Hidden dimension
latent_dim: 128
# Load/save directory
model_dir:
# Steerable attributes level
lmax-attributes: 1
# Level of the hidden layer
lmax-hidden: 1
# Normalization. instance, batch, none
norm: instance

# Optimization settings
# Batch size
batch_size: 2
# Starting learning rate
lr_start: 1e-4
# Final learning rate after decay
lr_final: 1e-6
# Rate of learning rate decay
lr_decay_rate: 0.1
# Number of steps for the learning rate to decay
lr_decay_steps: 5000000
# Standard deviation for the additive noise
noise_std: 0.00067
# Logarithmic normalization. none, input, output, both
log_norm: none

# Dataset settings
# Dataset directory
data_dir:
# Whether to use magnitudes or not
magnitudes: False
# Method to aggregate velocity. avg, sum, last, all
velocity_aggregate: avg
# Method to compose attributes. add, concat
attribute_mode: add

# Run settings
# train, eval
mode:
# Max steps
step_max: 20000000
# Number of evaluation trajectories
eval_num_trajs: 5
# Number of extrapolation steps
eval_n_more_steps: 0
# Seed
seed: 0

# Logging settings
# Use wandb for logging
wandb: false
# Number of steps between training logging
log_steps: 1000
# Number of steps between evaluation
eval_steps: 5000
# Number of steps between checkpoints
save_steps: 5000
# Checkpoint directory
ckp_dir: ckp
# Rollout/metrics directory
rollout_dir:
# Rollout storage format. vtk, pkl, none
out_type: none
# List of metrics. mse, mae, sinkhorn, emd, e_kin
metrics:
  - mse
