includes: defaults.yaml

model: gns
num_mp_steps: 5
num_mlp_layers: 1
latent_dim: 128

batch_size: 1
lr_start: 5.e-4
lr_final: 1.e-6
noise_std: 1.e-3
lr_decay_steps: 3.e+5

mode: train
eval_num_trajs: 1

wandb: True
wandb_project: tgv

data_dir: /home/atoshev/data/TGV1k12
