includes: defaults.yaml

model: gns
num_mp_steps: 5
num_mlp_layers: 1
latent_dim: 128

lr_start: 5.e-4
lr_final: 1.e-6
noise_std: 1.e-5
lr_decay_steps: 3.e+5

mode: train

data_dir: /home/atoshev/data/TGVCoarse
