includes: defaults.yaml

model: segnn_attention
num_mp_steps: 5
latent_dim: 64

batch_size: 1
lr_start: 5.e-4
lr_final: 1.e-6
noise_std: 1.e-4
lr_decay_steps: 2.e+5
isotropic_norm: True
attention_blocks: 1 # non-linear
right_attribute: False
velocity_aggregate: all

mode: train
eval_num_trajs: 1

wandb: True
wandb_project: rpf

data_dir: /home/atoshev/data/RPF100k1every10
