includes: defaults.yaml

model: segnn
num_mp_steps: 7
latent_dim: 32

batch_size: 1
lr_start: 5.e-4
lr_decay_steps: 1.e+5
noise_std: 3.e-5
isotropic_norm: True

mode: train
eval_num_trajs: 10
split_valid_traj_into_n: 10

wandb: True
wandb_project: rpf

data_dir: /home/atoshev/data/RPF100k1every10
