includes: defaults.yaml

model: segnn_attention
num_mp_steps: 5
latent_dim: 16

batch_size: 100
lr_start: 5.e-4
lr_final: 1.e-6
noise_std: 5.e-4
lr_decay_steps: 3.e+5
isotropic_norm: True
attention_blocks: 2 # non-linear
velocity_aggregate: all

segnn_norm: none

mode: train
eval_num_trajs: 1

log_steps: 50
eval_steps: 200
save_steps: 200

wandb: False
wandb_project: tgv

data_dir: /home/atoshev/data/LJ_debug
