includes: defaults.yaml

model: segnn_attention
num_mp_steps: 7
latent_dim: 32

batch_size: 1
lr_start: 5.e-4
lr_decay_steps: 1.e+5
noise_std: 1.e-4
isotropic_norm: True

right_attribute: False
attention_blocks: 1 # 1 corresponds to linear
velocity_aggregate: all
segnn_norm: none

mode: train
eval_num_trajs: 1

wandb: True
wandb_project: tgv10

data_dir: /home/atoshev/data/TGV1k100every10
