main:
  data_dir: datasets/2D_LDC_2708_10kevery100

model: 
  name: segnn
  num_mp_steps: 10
  latent_dim: 64

train:
  isotropic_norm: True

optimizer:
  lr_start: 5.e-4
  noise_std: 0.001

logging:
  wandb_project: ldc_2d

neighbors:
  multiplier: 2.0