extends: lagrangebench/defaults.py

main:
  dataset_path: datasets/3D_RPF_8000_10kevery100

model: 
  name: egnn
  num_mp_steps: 5
  latent_dim: 128
  isotropic_norm: True
  magnitude_features: True

train:
  optimizer:
    lr_start: 1.e-4
  loss_weight:
    pos: 1.0
    vel: 0.0
    acc: 0.0

logging:
  wandb_project: rpf_3d
