extends: LAGRANGEBENCH_DEFAULTS

main:
  dataset_path: datasets/3D_RPF_8000_10kevery100

model: 
  name: painn
  num_mp_steps: 5
  latent_dim: 128
  isotropic_norm: True
  magnitude_features: True

train:
  optimizer:
    lr_start: 5.e-4

logging:
  wandb_project: rpf_3d
