extends: LAGRANGEBENCH_DEFAULTS

main:
  dataset_path: datasets/3D_RPF_8000_10kevery100

model: 
  name: segnn
  num_mp_steps: 10
  latent_dim: 64
  isotropic_norm: True

train:
  optimizer:
    lr_start: 1.e-3

logging:
  wandb_project: rpf_3d
