data_dir: datasets/2D_RPF_3200_20kevery100

model: 
  name: egnn
  num_mp_steps: 5
  latent_dim: 128

train:
  isotropic_norm: True
  magnitude_features: True

optimizer:
  lr_start: 5.e-4
  loss_weight:
    pos: 1.0
    vel: 0.0
    acc: 0.0

logging:
  wandb_project: rpf_2d
