extends: rpf_2d/base.yaml

model: egnn
num_mp_steps: 1
latent_dim: 64

batch_size: 1
lr_start: 1.e-5
lr_decay_steps: 1.e+5
pushforward:
  steps: [-1, 100000, 125000, 150000, 175000, 200000]
  unrolls: [0, 1, 2, 3, 4, 5]
  probs: [16, 2, 1, 1, 1, 1]

noise_std: 3.e-7
magnitudes: True

loss_weight:
  pos: 0.0
  vel: 0.0
  acc: 1.0
