extends: lagrangebench/defaults.py

main:
  dataset_path: datasets/2D_RPF_3200_20kevery100

model: 
  name: gns
  num_mp_steps: 10
  latent_dim: 128

train:
  optimizer:
    lr_start: 5.e-4

logging:
  wandb_project: rpf_2d